### ISSUE TITLE
Подкапотное дело регистрации

### ISSUE THREAD

**Issue by NikolyaTruLaLaLa** [NikolyaTruLaLaLa/RingsOfWisdom#1]
**название ветки**
IlyaArea

**содержание**
1) сделать функционал регистрации на основе гайдов
2) На первых порах, сохранять данные в локальные файлы. В дальнейшем в базу данных, как только появятся ключи. Их сделает Коля.
3.1) сделать собственный простой html файлик для тестирования, потом заменить его на то, что сделает Саша.
3.2) сделать простой html файлик для тестов с проверкой кода с почты; работа с Сашей
4) сделать валидацию пароля минимальные - 6 букв 3 цифры, 1 спецсимвол.
5) логин - сфедушная почта. Пример: niignatenko@sfedu.ru
6) отправка письма на почту со сгенерированным кодом.
7) ввод никнейма стринг
8) кнопка вход - перенаправление на страницу авторизации, то, что делает Виталя

**конечный результат**
у нас полноценная страница регистрации

**указание**
гайды индусов; 

**Образец, источник вдохновения**
![image](https://github.com/user-attachments/assets/2d3967fa-03ef-4030-a8a4-a81b4ffdfd35)

**Comment by WaterCatt** [comment]
Выполнено в 449aa8f3aa9a9ee304ba6a1e7913625fb723d6e0
