### ISSUE TITLE
Подкапотное дело авторизация

### ISSUE THREAD

**Issue by NikolyaTruLaLaLa** [NikolyaTruLaLaLa/RingsOfWisdom#2]
**название ветки**
VitalyArea

**содержание**
1) сделать функционал авторизации на основе гайдов.
2) На первых порах, сохранять данные в локальные файлы. В дальнейшем в базу данных, как только появятся ключи. Их сделает Коля.
3) сделать собственный простой html файлик для тестирования, потом заменить его на то, что сделает Рома.
4) сделать валидацию пароля минимальные - 6 букв 3 цифры, 1 спецсимвол
5) логин - сфедушная почта. Пример: niignatenko@sfedu.ru
6) кнопка забыли пароль - заглушка в виде  процедуры
7) кнопка регистрация - перенаправление на страницу, что делает Илья
8) кнопка вход

**конечный результат**
можно будет авторизовываться

**указание**
Илья делает похожую по форме работу - регистрацию. Работать с ним в паре.

**Образец, источник вдохновения**
![image](https://github.com/user-attachments/assets/4ecb8018-9624-461c-b081-221aa6670f95)

**Comment by WaterCatt** [comment]
Выполнено в 449aa8f3aa9a9ee304ba6a1e7913625fb723d6e0
